# CMake generated Testfile for 
# Source directory: C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests
# Build directory: C:/Users/p1419778/Downloads/SimbodyBuild/Simbody/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GazeboBasicControllerResponse "C:/Users/p1419778/Downloads/SimbodyBuild/GazeboBasicControllerResponse")
set_tests_properties(GazeboBasicControllerResponse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(GazeboInelasticCollision "C:/Users/p1419778/Downloads/SimbodyBuild/GazeboInelasticCollision")
set_tests_properties(GazeboInelasticCollision PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(GazeboReactionForce "C:/Users/p1419778/Downloads/SimbodyBuild/GazeboReactionForce")
set_tests_properties(GazeboReactionForce PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(GazeboReactionForceWithAppliedForceCompliant "C:/Users/p1419778/Downloads/SimbodyBuild/GazeboReactionForceWithAppliedForceCompliant")
set_tests_properties(GazeboReactionForceWithAppliedForceCompliant PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(GazeboReactionForceWithAppliedForceRigid "C:/Users/p1419778/Downloads/SimbodyBuild/GazeboReactionForceWithAppliedForceRigid")
set_tests_properties(GazeboReactionForceWithAppliedForceRigid PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestAngleConversions "C:/Users/p1419778/Downloads/SimbodyBuild/TestAngleConversions")
set_tests_properties(TestAngleConversions PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestCollisionDetectionAlgorithm "C:/Users/p1419778/Downloads/SimbodyBuild/TestCollisionDetectionAlgorithm")
set_tests_properties(TestCollisionDetectionAlgorithm PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestConstraints "C:/Users/p1419778/Downloads/SimbodyBuild/TestConstraints")
set_tests_properties(TestConstraints PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestCustomConstraints "C:/Users/p1419778/Downloads/SimbodyBuild/TestCustomConstraints")
set_tests_properties(TestCustomConstraints PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestCustomMobilizedBodies "C:/Users/p1419778/Downloads/SimbodyBuild/TestCustomMobilizedBodies")
set_tests_properties(TestCustomMobilizedBodies PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestElasticFoundationForce "C:/Users/p1419778/Downloads/SimbodyBuild/TestElasticFoundationForce")
set_tests_properties(TestElasticFoundationForce PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestForces "C:/Users/p1419778/Downloads/SimbodyBuild/TestForces")
set_tests_properties(TestForces PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestFunctionBasedMobilizedBodies "C:/Users/p1419778/Downloads/SimbodyBuild/TestFunctionBasedMobilizedBodies")
set_tests_properties(TestFunctionBasedMobilizedBodies PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestGravity "C:/Users/p1419778/Downloads/SimbodyBuild/TestGravity")
set_tests_properties(TestGravity PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestHuntCrossleyForce "C:/Users/p1419778/Downloads/SimbodyBuild/TestHuntCrossleyForce")
set_tests_properties(TestHuntCrossleyForce PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestLinearBushing "C:/Users/p1419778/Downloads/SimbodyBuild/TestLinearBushing")
set_tests_properties(TestLinearBushing PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestLoneParticle "C:/Users/p1419778/Downloads/SimbodyBuild/TestLoneParticle")
set_tests_properties(TestLoneParticle PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestMassMatrix "C:/Users/p1419778/Downloads/SimbodyBuild/TestMassMatrix")
set_tests_properties(TestMassMatrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestMobilizedBody "C:/Users/p1419778/Downloads/SimbodyBuild/TestMobilizedBody")
set_tests_properties(TestMobilizedBody PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestMobilizerReactionForces "C:/Users/p1419778/Downloads/SimbodyBuild/TestMobilizerReactionForces")
set_tests_properties(TestMobilizerReactionForces PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestNoseHooverThermostat "C:/Users/p1419778/Downloads/SimbodyBuild/TestNoseHooverThermostat")
set_tests_properties(TestNoseHooverThermostat PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestObservedPointFitter "C:/Users/p1419778/Downloads/SimbodyBuild/TestObservedPointFitter")
set_tests_properties(TestObservedPointFitter PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestOrientedBoundingBox "C:/Users/p1419778/Downloads/SimbodyBuild/TestOrientedBoundingBox")
set_tests_properties(TestOrientedBoundingBox PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestParallelForces "C:/Users/p1419778/Downloads/SimbodyBuild/TestParallelForces")
set_tests_properties(TestParallelForces PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestPimpl1 "C:/Users/p1419778/Downloads/SimbodyBuild/TestPimpl1")
set_tests_properties(TestPimpl1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
add_test(TestReverseMobilizers "C:/Users/p1419778/Downloads/SimbodyBuild/TestReverseMobilizers")
set_tests_properties(TestReverseMobilizers PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/Simbody/tests/CMakeLists.txt;0;")
subdirs("adhoc")
