# CMake generated Testfile for 
# Source directory: C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests
# Build directory: C:/Users/p1419778/Downloads/SimbodyBuild/SimTKcommon/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BNTTest "C:/Users/p1419778/Downloads/SimbodyBuild/BNTTest")
set_tests_properties(BNTTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(MatVecTest "C:/Users/p1419778/Downloads/SimbodyBuild/MatVecTest")
set_tests_properties(MatVecTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(OrientationTest "C:/Users/p1419778/Downloads/SimbodyBuild/OrientationTest")
set_tests_properties(OrientationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(PolynomialTest "C:/Users/p1419778/Downloads/SimbodyBuild/PolynomialTest")
set_tests_properties(PolynomialTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(RandomTest "C:/Users/p1419778/Downloads/SimbodyBuild/RandomTest")
set_tests_properties(RandomTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(RotationTest "C:/Users/p1419778/Downloads/SimbodyBuild/RotationTest")
set_tests_properties(RotationTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(SFMTTest "C:/Users/p1419778/Downloads/SimbodyBuild/SFMTTest")
set_tests_properties(SFMTTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(SpatialAlgebraTest "C:/Users/p1419778/Downloads/SimbodyBuild/SpatialAlgebraTest")
set_tests_properties(SpatialAlgebraTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(StateTest "C:/Users/p1419778/Downloads/SimbodyBuild/StateTest")
set_tests_properties(StateTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestArray "C:/Users/p1419778/Downloads/SimbodyBuild/TestArray")
set_tests_properties(TestArray PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestAtomic "C:/Users/p1419778/Downloads/SimbodyBuild/TestAtomic")
set_tests_properties(TestAtomic PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestBigMatrix "C:/Users/p1419778/Downloads/SimbodyBuild/TestBigMatrix")
set_tests_properties(TestBigMatrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestCloneOnWritePtr "C:/Users/p1419778/Downloads/SimbodyBuild/TestCloneOnWritePtr")
set_tests_properties(TestCloneOnWritePtr PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestFunction "C:/Users/p1419778/Downloads/SimbodyBuild/TestFunction")
set_tests_properties(TestFunction PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestIteratorRange "C:/Users/p1419778/Downloads/SimbodyBuild/TestIteratorRange")
set_tests_properties(TestIteratorRange PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestMassProperties "C:/Users/p1419778/Downloads/SimbodyBuild/TestMassProperties")
set_tests_properties(TestMassProperties PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestNiceTypeName "C:/Users/p1419778/Downloads/SimbodyBuild/TestNiceTypeName")
set_tests_properties(TestNiceTypeName PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestParallel2DExecutor "C:/Users/p1419778/Downloads/SimbodyBuild/TestParallel2DExecutor")
set_tests_properties(TestParallel2DExecutor PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestParallelExecutor "C:/Users/p1419778/Downloads/SimbodyBuild/TestParallelExecutor")
set_tests_properties(TestParallelExecutor PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestParallelWorkQueue "C:/Users/p1419778/Downloads/SimbodyBuild/TestParallelWorkQueue")
set_tests_properties(TestParallelWorkQueue PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestPlugin "C:/Users/p1419778/Downloads/SimbodyBuild/TestPlugin")
set_tests_properties(TestPlugin PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestPolygonalMesh "C:/Users/p1419778/Downloads/SimbodyBuild/TestPolygonalMesh")
set_tests_properties(TestPolygonalMesh PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestPrivateImplementation "C:/Users/p1419778/Downloads/SimbodyBuild/TestPrivateImplementation")
set_tests_properties(TestPrivateImplementation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestScalar "C:/Users/p1419778/Downloads/SimbodyBuild/TestScalar")
set_tests_properties(TestScalar PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestSimulation "C:/Users/p1419778/Downloads/SimbodyBuild/TestSimulation")
set_tests_properties(TestSimulation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestSmallMatrix "C:/Users/p1419778/Downloads/SimbodyBuild/TestSmallMatrix")
set_tests_properties(TestSmallMatrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestVectorMath "C:/Users/p1419778/Downloads/SimbodyBuild/TestVectorMath")
set_tests_properties(TestVectorMath PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
add_test(TestXml "C:/Users/p1419778/Downloads/SimbodyBuild/TestXml")
set_tests_properties(TestXml PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;36;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKcommon/tests/CMakeLists.txt;0;")
subdirs("adhoc")
