# CMake generated Testfile for 
# Source directory: C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests
# Build directory: C:/Users/p1419778/Downloads/SimbodyBuild/SimTKmath/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BestAvailableTest "C:/Users/p1419778/Downloads/SimbodyBuild/BestAvailableTest")
set_tests_properties(BestAvailableTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(CMAESTest "C:/Users/p1419778/Downloads/SimbodyBuild/CMAESTest")
set_tests_properties(CMAESTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(CPodesIntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/CPodesIntegratorTest")
set_tests_properties(CPodesIntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(DifferentiatorTest "C:/Users/p1419778/Downloads/SimbodyBuild/DifferentiatorTest")
set_tests_properties(DifferentiatorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(EigenTest "C:/Users/p1419778/Downloads/SimbodyBuild/EigenTest")
set_tests_properties(EigenTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(ExplicitEulerIntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/ExplicitEulerIntegratorTest")
set_tests_properties(ExplicitEulerIntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(FactorLUTest "C:/Users/p1419778/Downloads/SimbodyBuild/FactorLUTest")
set_tests_properties(FactorLUTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(FactorQTZTest "C:/Users/p1419778/Downloads/SimbodyBuild/FactorQTZTest")
set_tests_properties(FactorQTZTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(FactorSVDTest "C:/Users/p1419778/Downloads/SimbodyBuild/FactorSVDTest")
set_tests_properties(FactorSVDTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(IntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/IntegratorTest")
set_tests_properties(IntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(IpoptDiffTest "C:/Users/p1419778/Downloads/SimbodyBuild/IpoptDiffTest")
set_tests_properties(IpoptDiffTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(IpoptTest "C:/Users/p1419778/Downloads/SimbodyBuild/IpoptTest")
set_tests_properties(IpoptTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(LBFGSBDiffTest "C:/Users/p1419778/Downloads/SimbodyBuild/LBFGSBDiffTest")
set_tests_properties(LBFGSBDiffTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(LBFGSBTest "C:/Users/p1419778/Downloads/SimbodyBuild/LBFGSBTest")
set_tests_properties(LBFGSBTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(LBFGSDiffTest "C:/Users/p1419778/Downloads/SimbodyBuild/LBFGSDiffTest")
set_tests_properties(LBFGSDiffTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(LBFGSTest "C:/Users/p1419778/Downloads/SimbodyBuild/LBFGSTest")
set_tests_properties(LBFGSTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(RungeKutta2IntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/RungeKutta2IntegratorTest")
set_tests_properties(RungeKutta2IntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(RungeKutta3IntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/RungeKutta3IntegratorTest")
set_tests_properties(RungeKutta3IntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(RungeKuttaFeldbergIntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/RungeKuttaFeldbergIntegratorTest")
set_tests_properties(RungeKuttaFeldbergIntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(RungeKuttaMersonIntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/RungeKuttaMersonIntegratorTest")
set_tests_properties(RungeKuttaMersonIntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(SemiExplicitEuler2IntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/SemiExplicitEuler2IntegratorTest")
set_tests_properties(SemiExplicitEuler2IntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(SemiExplicitEulerIntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/SemiExplicitEulerIntegratorTest")
set_tests_properties(SemiExplicitEulerIntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(SimpleDifferentiatorTest "C:/Users/p1419778/Downloads/SimbodyBuild/SimpleDifferentiatorTest")
set_tests_properties(SimpleDifferentiatorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TestBicubicSurface "C:/Users/p1419778/Downloads/SimbodyBuild/TestBicubicSurface")
set_tests_properties(TestBicubicSurface PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TestContactGeometry "C:/Users/p1419778/Downloads/SimbodyBuild/TestContactGeometry")
set_tests_properties(TestContactGeometry PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TestGeo "C:/Users/p1419778/Downloads/SimbodyBuild/TestGeo")
set_tests_properties(TestGeo PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TestMultibodyGraphMaker "C:/Users/p1419778/Downloads/SimbodyBuild/TestMultibodyGraphMaker")
set_tests_properties(TestMultibodyGraphMaker PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TestSpline "C:/Users/p1419778/Downloads/SimbodyBuild/TestSpline")
set_tests_properties(TestSpline PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TestTriangleMesh "C:/Users/p1419778/Downloads/SimbodyBuild/TestTriangleMesh")
set_tests_properties(TestTriangleMesh PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(TimeStepperTest "C:/Users/p1419778/Downloads/SimbodyBuild/TimeStepperTest")
set_tests_properties(TimeStepperTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
add_test(VerletIntegratorTest "C:/Users/p1419778/Downloads/SimbodyBuild/VerletIntegratorTest")
set_tests_properties(VerletIntegratorTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;41;add_test;C:/Users/p1419778/Downloads/simbody-Simbody-3.6.1/simbody-Simbody-3.6.1/SimTKmath/tests/CMakeLists.txt;0;")
subdirs("adhoc")
